# Autogenerated by devscripts/update-version.py

__version__ = '2024.04.01.182951'

RELEASE_GIT_HEAD = 'e5d4f11104ce7ea1717a90eea82c0f7d230ea5d5'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Flame239/yt-dlp-afreeca-fix'

ORIGIN = 'Flame239/yt-dlp-afreeca-fix'

_pkg_version = '2024.04.01.182951'
