# Autogenerated by devscripts/update-version.py

__version__ = '2024.04.01.190106'

RELEASE_GIT_HEAD = 'd5471fbbc7371fa8ab2c3dc0105001adde691bd1'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Flame239/yt-dlp-afreeca-fix'

ORIGIN = 'Flame239/yt-dlp-afreeca-fix'

_pkg_version = '2024.04.01.190106'
